### ISSUE TITLE
Eraware Dnn SPA EF CI Stencil Module Template Load Component Assembly Error

### ISSUE THREAD

**Issue by Calix-Mushroom** [valadas/Eraware_Dnn_Templates#835]
Versioning of .NET and Microsoft Visual Studio 2022 is incompatible with Eraware Dnn SPA EF CI Stencil Module Template v.1.10.0 that was compatible with v.1.9.0. Specifically, .NET Framework 4.8.1 and Visual Studio 2022 v.17.12-v.17.14.14. The problem probably extends from incompatible versioning or missing extensions with Visual Studio 2022 that was not needed in v.1.9.0. Documentation of necessary extensions or compatibility fixes may be needed. Attached is the exact error code:

<img width="453" height="174" alt="Image" src="https://github.com/user-attachments/assets/ef225313-62b3-49f5-9f37-a283c8bb8594" />

**Comment by valadas** [comment]
I think there may be some issue between the wizard version vs the vsix version here. I should be working on this probably this weekend and I'll ping you for testing a potential update...

**Comment by valadas** [comment]
@Calix-Mushroom can you try if this build works for you https://github.com/valadas/Eraware_Dnn_Templates/actions/runs/18051831908/artifacts/4119941110
That will be a zip, extract it first and you will have a vsix inside to install it.

Report back if that works or not and if you get a different error, let me know, I am working on updates a bit tonight on this project.
Thanks.

**Comment by Calix-Mushroom** [comment]
I tried the new build but am still getting the same error message. It could be a compiling error with a package versioning mismatch. Is there a way to view the different packaging versioning in Eraware to check if they align with mine? 
Thanks.

**Comment by valadas** [comment]
@Calix-Mushroom can you give this one a test https://github.com/valadas/Eraware_Dnn_Templates/actions/runs/18181818244/artifacts/4161138079

I fixed a few issues with versioning that may fix that problem. If you still get that error check if it still is looking for 1.0.0.0 or not.
And if that is still a problem, try clearing your template caches and installing again. 

To clear the templates cache you can run these 2 commands in powershell (probably needs to run as admin)

```powershell
Remove-Item "$env:LOCALAPPDATA\Microsoft\VisualStudio\*\ProjectTemplatesCache" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item "$env:LOCALAPPDATA\Microsoft\VisualStudio\*\ItemTemplatesCache" -Recurse -Force -ErrorAction SilentlyContinue
```

Let me know how that goes, if it works, I have a few more things to update and I'll push a release soon...

**Comment by Calix-Mushroom** [comment]
This new installation fixed the error and it appears to be running well. Thanks a bunch, I look forward to the new release.

**Comment by valadas** [comment]
Awesome, what for next release and when it gets out, you should uninstall the current and install the new (as they will have the same version so may refuse to install...
Thanks for sticking around while I worked through that.

**Comment by valadas** [comment]
Ok @Calix-Mushroom I have just published v1.11.1 to the visual studio extensions marketplace, so you should have that after they finish verification (which usually takes 5-10 minutes). Let me know if you run into other issues.
